name: sqllite_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  nb_utils: ^7.0.7
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

  ## LOCAL DATABASE
  sqflite: ^2.3.3+1
  path: 1.9.0
  path_provider: ^2.1.5

  ## State Management
  get: ^4.6.6

  ## Image Picker
  image_picker: ^0.8.7+3

  ## Local Storage
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg